# Generated by Django 4.2.7 on 2024-01-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_reenteremail_school_re_enteremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='smail',
            new_name='email',
        ),
    ]
